# Generated by Django 5.2.4 on 2025-07-13 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura em graus Celsius.', max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, help_text='Umidade relativa do ar em porcentagem.', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da leitura do sensor.')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='iot_core.dispositivo')),
            ],
            options={
                'verbose_name': 'Leitura de Sensor',
                'verbose_name_plural': 'Leituras de Sensores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
