# Generated by Django 5.2.4 on 2025-07-14 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0002_leiturasensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(help_text="O comando a ser enviado (ex: 'LIGAR_AR', 'BUZZER_ON').", max_length=100)),
                ('parametros', models.TextField(blank=True, help_text='Parâmetros adicionais para o comando (JSON opcional).', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora que o comando foi criado.')),
                ('executado', models.BooleanField(default=False, help_text='Indica se o comando já foi executado pelo dispositivo.')),
                ('data_execucao', models.DateTimeField(blank=True, help_text='Data e hora que o comando foi executado.', null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos_pendentes', to='iot_core.dispositivo')),
            ],
            options={
                'verbose_name': 'Comando Pendente',
                'verbose_name_plural': 'Comandos Pendentes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
