# Generated by Django 5.2.4 on 2025-07-14 05:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0003_comandopendente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandopendente',
            options={},
        ),
        migrations.RemoveField(
            model_name='comandopendente',
            name='data_execucao',
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='data_execucao_agendada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='data_execucao_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='comando',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_core.dispositivo'),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='executado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
