# Generated by Django 5.2.4 on 2025-07-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0004_alter_comandopendente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandopendente',
            options={'ordering': ['data_execucao_agendada']},
        ),
        migrations.RenameField(
            model_name='comandopendente',
            old_name='data_criacao',
            new_name='data_agendamento',
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='data_fim_repeticao',
            field=models.DateField(blank=True, help_text='Data em que a repetição deve parar (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='dias_da_semana',
            field=models.CharField(blank=True, help_text='Dias da semana para repetição semanal (0=Seg, 1=Ter, ..., 6=Dom). Separados por vírgula.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='is_master_repetitive',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, este é um comando mestre que gera repetições.'),
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='master_command_id',
            field=models.IntegerField(blank=True, help_text='ID do comando mestre que gerou esta instância repetida.', null=True),
        ),
        migrations.AddField(
            model_name='comandopendente',
            name='tipo_repeticao',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('diario', 'Diário'), ('semanal', 'Semanal')], default='nenhum', help_text='Define se o comando deve se repetir.', max_length=10),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='comando',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comandopendente',
            name='data_execucao_agendada',
            field=models.DateTimeField(),
        ),
    ]
