# Generated by Django 5.2.4 on 2025-07-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0005_alter_comandopendente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditionerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID único do dispositivo IoT (ex: MAC, serial)', max_length=100)),
                ('action', models.CharField(choices=[('LIGAR', 'Ligar'), ('DESLIGAR', 'Desligar')], help_text='Ação executada no ar condicionado', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Data e hora da ação')),
                ('success', models.BooleanField(default=True, help_text='Indica se a ação foi bem-sucedida')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais (ex: erro, motivo)', null=True)),
            ],
            options={
                'verbose_name': 'Log do Ar Condicionado',
                'verbose_name_plural': 'Logs do Ar Condicionado',
                'ordering': ['-timestamp'],
            },
        ),
    ]
