# Generated by Django 5.2.4 on 2025-07-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_core', '0006_airconditionerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do dispositivo (ex: Ar Sala, Ar Quarto)', max_length=100, unique=True)),
                ('device_id', models.CharField(help_text='ID único do dispositivo para comunicação IoT (ex: MAC, serial)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do dispositivo', null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('device', models.OneToOneField(help_text='O dispositivo IoT associado a este estado.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iot_core.iotdevice')),
                ('is_on', models.BooleanField(default=False, help_text='True se o dispositivo estiver ligado, False se estiver desligado.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última vez que o estado foi atualizado.')),
            ],
            options={
                'verbose_name': 'Estado do Dispositivo',
                'verbose_name_plural': 'Estados dos Dispositivos',
            },
        ),
    ]
